### ISSUE TITLE
crash when discovery

### ISSUE THREAD

**Issue by Lemecducoin** [vmartos/OnvifSharp#21]
Some onvif system make crash the fonction DiscoveryDevice.
Because they send a null header. Like hikvision decoder.

To correct this i have add this in :
 ```
private DiscoveryDevice ProcessResponse(UdpReceiveResult response, Guid messageId)
        {
            if (response.Buffer != null)
            {
                string strResponse = Encoding.UTF8.GetString(response.Buffer);
                XmlProbeReponse xmlResponse = DeserializeResponse(strResponse);
                if (*_***xmlResponse.Header != null**_** && IsFromProbeMessage(messageId, xmlResponse)
                    && xmlResponse.Body.ProbeMatches.Any()
                    && !string.IsNullOrEmpty(xmlResponse.Body.ProbeMatches[0].Scopes))
                {
                    return DeviceFactory.CreateDevice(xmlResponse.Body.ProbeMatches[0], response.RemoteEndPoint);
                }
            }
            return null;
        }
```

**Comment by vicmaeg** [comment]
Hi @Lemecducoin,

The code should not crash (at least in the newest version of the library) because there is a catch (Exception), but in any case it is a good idea to check for null instead of throwing and the catching the exception.

I created a PR to check for null, to avoid throwing an exception: https://github.com/vmartos/onvif-discovery/pull/22

I will merge it as soon as checks passes and create a new version of the library.

Thanks for creating the issue!
